// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARXddwe_1E9-ALRbn97VLbl3wjZ2ZB3dI',
    appId: '1:434521031425:web:b979e88637945731f19100',
    messagingSenderId: '434521031425',
    projectId: 'appstreewalletapp',
    authDomain: 'appstreewalletapp.firebaseapp.com',
    storageBucket: 'appstreewalletapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFY9lOL4O5hbFcP7m_f9mVrT6nyLHWIzA',
    appId: '1:434521031425:android:af575c4869e1a387f19100',
    messagingSenderId: '434521031425',
    projectId: 'appstreewalletapp',
    storageBucket: 'appstreewalletapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh4m5ZDBym1s7heCGW5k6DZQtc-rTlW8Q',
    appId: '1:434521031425:ios:2289548e4ea439eff19100',
    messagingSenderId: '434521031425',
    projectId: 'appstreewalletapp',
    storageBucket: 'appstreewalletapp.appspot.com',
    iosBundleId: 'com.example.walletapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh4m5ZDBym1s7heCGW5k6DZQtc-rTlW8Q',
    appId: '1:434521031425:ios:051b3e5dd9ee9fa0f19100',
    messagingSenderId: '434521031425',
    projectId: 'appstreewalletapp',
    storageBucket: 'appstreewalletapp.appspot.com',
    iosBundleId: 'com.example.walletapp.RunnerTests',
  );
}
